-- Run this in Supabase SQL editor
create table experiments (
  id bigint generated by default as identity primary key,
  title text not null,
  hypothesis text,
  description text,
  cta_text text not null default 'Try it',
  cta_type text not null default 'link', -- 'link' or 'email'
  cta_destination text, -- url or null
  public_slug text unique not null,
  status text not null default 'active', -- 'active', 'paused', 'completed'
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table submissions (
  id bigint generated by default as identity primary key,
  experiment_id bigint references experiments(id) on delete cascade,
  email text,
  created_at timestamptz default now(),
  unique(experiment_id, email)
);

create table events (
  id bigint generated by default as identity primary key,
  experiment_id bigint references experiments(id) on delete cascade,
  event_type text not null, -- 'view', 'cta_click', 'signup'
  metadata jsonb,
  created_at timestamptz default now()
);

create index idx_events_experiment_id on events(experiment_id);
create index idx_events_event_type on events(event_type);
create index idx_events_created_at on events(created_at);
create index idx_experiments_status on experiments(status);
