-- Run this in Supabase SQL editor
create table experiments (
  id bigint generated by default as identity primary key,
  title text not null,
  hypothesis text,
  description text,
  cta_text text not null default 'Try it',
  cta_type text not null default 'link', -- 'link' or 'email'
  cta_destination text, -- url or null
  public_slug text unique not null,
  created_at timestamptz default now()
);

create table submissions (
  id bigint generated by default as identity primary key,
  experiment_id bigint references experiments(id) on delete cascade,
  email text,
  created_at timestamptz default now()
);
